### ISSUE TITLE
IdentityRoles Collection

### ISSUE THREAD

**Issue by CR34L** [matteofabbri/Mongolino#5]
Creating Roles like this:

    var x = await _roleManager.RoleExistsAsync("Moderator");
    if (!x) {
       var role = new MongoIdentityRole();
       role.Name = "Manager";
       await _roleManager.CreateAsync(role);
    }

where stored into RoleCollection as expected. If I add a user to a custom role: 
`var roleResult = await _userManager.AddToRoleAsync(user, "Moderator");`
The user is attached to the role correctly. But the database structure seems to be wrong. The IdentityFramework stores roles in a separate collection and the role-user-relationship into the user object (user.roles = ["role1, role2"]).

So if I delete a user I also must delete all the role relations in this separate collection. Thats not a good approach.

**Comment by matteofabbri** [comment]
Opening the issue in the right repo was too difficult ?
Btw I'm making a lot of changes and improvment including this one

**Comment by CR34L** [comment]
My fault. I close the issue and reopen this in the correct repo.

///

**Comment by matteofabbri** [comment]
@CR34L I made a huge update based on cool stuff i found on the "original one".
Including this fix

https://github.com/matteofabbri/AspNetCore.Identity.Mongo
